### ISSUE TITLE
Array support

### ISSUE THREAD

**Issue by dieend** [sonots/fluent-plugin-record-reformer#18]
Is there any support for reforming fields into array?
e.g.
I have field `lon:0.2193` and field `lat:129.53`,
now I want the output is `coordinate:[0.2193,129.53]`
Is it possible using record reformer?

**Comment by sonots** [comment]
Hmm, nope

**Comment by Seraf** [comment]
Hello @sonots 

I saw you add the support of hash/json in https://github.com/sonots/fluent-plugin-record-reformer/commit/dd91d993d0e1624d825086b43a01b5497793b402 but I have some difficulty to use it.

I tried : 
```
<match **.access>
  type geoip

  # Specify one or more geoip lookup field which has ip address (default: host)
  # in the case of accessing nested value, delimit keys by dot like 'host.ip'.
  geoip_lookup_key  remote

  # Specify optional geoip database (using bundled GeoLiteCity databse by default)
  geoip_database    "/opt/td-agent/GeoLiteCity.dat"

  # Set adding field with placeholder (more than one settings are required.)
  <record>
    #city            ${city["remote"]}
    #geoip            {'coordinates': "${latitude["remote"]},${longitude["remote"]}", 'country': "${country_code["remote"]}"}
    #latitude        ${latitude["remote"]}
    #longitude       ${longitude["remote"]}
    #country_code3   ${country_code3["remote"]}
    #country         ${country_code["remote"]}
    #country_name    ${country_name["remote"]}
    #dma             ${dma_code["remote"]}
    #area            ${area_code["remote"]}
    #region          ${region["remote"]}
  </record>

  # Settings for tag
  tag               ${tag}.geoip
</match>
```

But it seems to fail : 
```
[....] Restarting td-agent: td-agent/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/config/basic_parser.rb:88:in `parse_error!': got incomplete JSON hash configuration at 50-match-nginx-geoip.conf line 27,9 (Fluent::ConfigParseError)
 26:   tag               ${tag}.geoip
 27: </match>

     ---------^
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/config/literal_parser.rb:236:in `scan_json'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/config/literal_parser.rb:59:in `parse_literal'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/config/v1_parser.rb:128:in `parse_element'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/config/v1_parser.rb:93:in `parse_element'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/config/v1_parser.rb:93:in `parse_element'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/config/v1_parser.rb:163:in `block in eval_include'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/config/v1_parser.rb:157:in `each'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/config/v1_parser.rb:157:in `eval_include'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/config/v1_parser.rb:143:in `parse_include'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/config/v1_parser.rb:102:in `parse_element'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/config/v1_parser.rb:41:in `parse!'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/config/v1_parser.rb:31:in `parse'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/config.rb:29:in `parse'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/supervisor.rb:356:in `read_config'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/supervisor.rb:126:in `start'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/lib/fluent/command/fluentd.rb:167:in `<top (required)>'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.7/bin/fluentd:6:in `<top (required)>'
	from /opt/td-agent/embedded/bin/fluentd:23:in `load'
	from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
	from /usr/sbin/td-agent:7:in `load'
	from /usr/sbin/td-agent:7:in `<main>'
 failed!
```

Any idea please ?

Thanks for your plugin !

**Comment by sonots** [comment]
This plugin is not geoip plugin.

**Comment by Seraf** [comment]
Hello, I'm sorry, I was thinking geoip used your plugin. I solved my
problem.

Sorry for the noise and thanks for your very quick answer !

This plugin is not geoip plugin.

—
Reply to this email directly or view it on GitHub
<https://github.com/sonots/fluent-plugin-record-reformer/issues/18#issuecomment-103131075>
.
